CREATE TABLE `fund_detail_info` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `fund_code` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '基金代码',
  `fund_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '基金简称',
  `fund_pinyin` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '基金拼音',
  `fund_date` date DEFAULT NULL COMMENT '基金日期',
  `net_asset_value` decimal(16,4) DEFAULT NULL COMMENT '单位净值',
  `accumulated_net` decimal(16,4) DEFAULT NULL COMMENT '累计净值',
  `daily_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '日增长率',
  `nearly_1_week` decimal(16,4) DEFAULT NULL COMMENT '近1周',
  `nearly_1_month` decimal(16,4) DEFAULT NULL COMMENT '近1月',
  `nearly_3_month` decimal(16,4) DEFAULT NULL COMMENT '近3月',
  `nearly_6_month` decimal(16,4) DEFAULT NULL COMMENT '近3月',
  `nearly_1_year` decimal(16,4) DEFAULT NULL COMMENT '近1年',
  `nearly_2_year` decimal(16,4) DEFAULT NULL COMMENT '近2年',
  `nearly_3_year` decimal(16,4) DEFAULT NULL COMMENT '近3年',
  `since_this_year` decimal(16,4) DEFAULT NULL COMMENT '今年以来',
  `since_establish` decimal(16,4) DEFAULT NULL COMMENT '成立以来',
  `establish_date` date DEFAULT NULL COMMENT '成立日期',
  `unknown_1` int DEFAULT NULL COMMENT '未知1',
  `custom` decimal(16,4) DEFAULT NULL COMMENT '自定义',
  `service_charge` decimal(16,4) DEFAULT NULL COMMENT '手续费',
  `discount_service_charge` decimal(16,4) DEFAULT NULL COMMENT '打折手续费',
  `discount` decimal(16,4) DEFAULT NULL COMMENT '折扣',
  `unknown_2` decimal(16,4) DEFAULT NULL COMMENT '未知2',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19378 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;