CREATE TABLE `fund_detail_info` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `fund_code` varchar(16) DEFAULT NULL COMMENT '基金代码',
  `fund_name` varchar(32) DEFAULT NULL COMMENT '基金简称',
  `fund_pinyin` varchar(32) DEFAULT NULL COMMENT '基金拼音',
  `fund_date` date DEFAULT NULL COMMENT '基金日期',
  `net_asset_value` decimal(16,4) DEFAULT NULL COMMENT '单位净值',
  `accumulated_net` decimal(16,4) DEFAULT NULL COMMENT '累计净值',
  `daily_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '日增长率',
  `nearly_1_week_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近1周增长率',
  `nearly_1_month_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近1月增长率',
  `nearly_3_month_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近3月增长率',
  `nearly_6_month_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近6月增长率',
  `nearly_1_year_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近1年增长率',
  `nearly_2_year_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近2年增长率',
  `nearly_3_year_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '近3年增长率',
  `since_this_year_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '今年以来增长率',
  `since_establish_grow_rate` decimal(16,4) DEFAULT NULL COMMENT '成立以来增长率',
  `nearly_1_year_wave_rate` decimal(16,4) DEFAULT NULL COMMENT '近1年波动率',
  `nearly_2_year_wave_rate` decimal(16,4) DEFAULT NULL COMMENT '近2年波动率',
  `nearly_3_year_wave_rate` decimal(16,4) DEFAULT NULL COMMENT '近3年波动率',
  `nearly_1_year_sharp_rate` decimal(16,4) DEFAULT NULL COMMENT '近1年夏普率',
  `nearly_2_year_sharp_rate` decimal(16,4) DEFAULT NULL COMMENT '近2年夏普率',
  `nearly_3_year_sharp_rate` decimal(16,4) DEFAULT NULL COMMENT '近3年夏普率',
  `establish_date` date DEFAULT NULL COMMENT '成立日期',
  `fund_manager` varchar(64) DEFAULT NULL COMMENT '基金经理',
  `manager_start_date` date DEFAULT NULL COMMENT '基金经理起始日期',
  `previous_fund_manager` varchar(64) DEFAULT NULL COMMENT '前任基金经理',
  `previous_manager_start_date` date DEFAULT NULL COMMENT '前任基金经理起始日期',
  `unknown_1` int DEFAULT NULL COMMENT '未知1',
  `custom` decimal(16,4) DEFAULT NULL COMMENT '自定义',
  `service_charge_rate` decimal(16,4) DEFAULT NULL COMMENT '手续费率',
  `discount_service_charge_rate` decimal(16,4) DEFAULT NULL COMMENT '打折手续费率',
  `discount_rate` decimal(16,4) DEFAULT NULL COMMENT '折扣率',
  `unknown_2` decimal(16,4) DEFAULT NULL COMMENT '未知2',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY idx_code (`fund_code`),
  KEY idx_time (`create_time`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;